"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-09-01 12:49:19.010466

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=True),
    sa.Column('commit_sha', sa.String(), nullable=True),
    sa.Column('repository_url', sa.String(), nullable=True),
    sa.Column('artifact_ref', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('DRAFT', 'ADMISSION', 'ADMISSION_FAILED', 'ANALYSING', 'NEEDS_REVIEW', 'AWAITING_APPROVAL', 'COMPLETED', 'EXPIRED', name='assessmentstate', native_enum=False, length=32), nullable=False),
    sa.Column('requester', sa.String(), nullable=False),
    sa.Column('requester_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment'))
    )
    op.create_table('audit_entry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=True),
    sa.Column('subject_id', sa.String(), nullable=True),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_entry'))
    )
    op.create_table('cve_profile',
    sa.Column('cve', sa.String(), nullable=False),
    sa.Column('intrinsic_json', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cve', name=op.f('pk_cve_profile'))
    )
    op.create_table('finding',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('cve', sa.String(), nullable=False),
    sa.Column('purl', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=True),
    sa.Column('violation_id_snapshot', sa.String(), nullable=True),
    sa.Column('threat_level', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Enum('NOT_AFFECTED', 'AFFECTED', 'NEEDS_REVIEW', 'RISK_ACCEPTANCE_REQUIRED', name='findingoutcome', native_enum=False, length=32), nullable=True),
    sa.Column('justification', sa.Enum('CODE_NOT_PRESENT', 'CODE_NOT_REACHABLE', 'REQUIRES_DEPENDENCY', 'REQUIRES_CONFIGURATION', 'REQUIRES_ENVIRONMENT', 'PROTECTED_AT_PERIMETER', 'PROTECTED_BY_MITIGATING_CONTROL', name='justification', native_enum=False, length=48), nullable=True),
    sa.Column('tier', sa.Enum('PROOF', 'STRONG', 'ESCALATION', name='evidencetier', native_enum=False, length=16), nullable=True),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT', name='confidence', native_enum=False, length=32), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], name=op.f('fk_finding_assessment_id_assessment'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finding')),
    sa.UniqueConstraint('assessment_id', 'cve', 'purl', name=op.f('uq_finding_assessment_id'))
    )
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_assessment_id'), ['assessment_id'], unique=False)

    op.create_table('ai_verdict',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('NOT_AFFECTED', 'AFFECTED', 'UNDER_INVESTIGATION', name='state', native_enum=False, length=32), nullable=False),
    sa.Column('justification', sa.Enum('CODE_NOT_PRESENT', 'CODE_NOT_REACHABLE', 'REQUIRES_DEPENDENCY', 'REQUIRES_CONFIGURATION', 'REQUIRES_ENVIRONMENT', 'PROTECTED_AT_PERIMETER', 'PROTECTED_BY_MITIGATING_CONTROL', name='justification', native_enum=False, length=48), nullable=True),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'INSUFFICIENT', name='confidence', native_enum=False, length=32), nullable=False),
    sa.Column('evidence_refs_json', sa.JSON(), nullable=False),
    sa.Column('missing_evidence_json', sa.JSON(), nullable=False),
    sa.Column('refuted_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], name=op.f('fk_ai_verdict_finding_id_finding'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_verdict'))
    )
    with op.batch_alter_table('ai_verdict', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_verdict_finding_id'), ['finding_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=True),
    sa.Column('collector', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], name=op.f('fk_evidence_assessment_id_assessment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], name=op.f('fk_evidence_finding_id_finding')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_finding_id'), ['finding_id'], unique=False)

    op.create_table('iq_determination_link',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('policy_waiver_id', sa.String(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], name=op.f('fk_iq_determination_link_finding_id_finding'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_iq_determination_link'))
    )
    with op.batch_alter_table('iq_determination_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_iq_determination_link_finding_id'), ['finding_id'], unique=False)

    op.create_table('rule_result',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('rule_version', sa.String(), nullable=False),
    sa.Column('verdict', sa.Enum('NOT_AFFECTED', 'AFFECTED', 'UNDER_INVESTIGATION', name='state', native_enum=False, length=32), nullable=False),
    sa.Column('tier', sa.Enum('PROOF', 'STRONG', 'ESCALATION', name='evidencetier', native_enum=False, length=16), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['finding.id'], name=op.f('fk_rule_result_finding_id_finding'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_result'))
    )
    with op.batch_alter_table('rule_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_result_finding_id'), ['finding_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_result_finding_id'))

    op.drop_table('rule_result')
    with op.batch_alter_table('iq_determination_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_iq_determination_link_finding_id'))

    op.drop_table('iq_determination_link')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_finding_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_assessment_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('ai_verdict', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_verdict_finding_id'))

    op.drop_table('ai_verdict')
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_assessment_id'))

    op.drop_table('finding')
    op.drop_table('cve_profile')
    op.drop_table('audit_entry')
    op.drop_table('assessment')
    # ### end Alembic commands ###
