"""add user table

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-01 18:00:46.709220

Hand-reviewed after autogenerate: the generated file rendered `created_at`'s
type as the bare `app.repos.models.UtcDateTime()`, with no import for
`app.repos.models` anywhere in the file — it would have raised `NameError`
the moment this migration ran. Every timestamp column in `0001_initial.py`
(generated the same way, for the same `UtcDateTime` type_annotation_map
entry) renders as plain `sa.DateTime()` instead, which compiles to the
identical column type: `UtcDateTime.impl = DateTime` means only Python-level
bind/result processing differs, never the schema DDL (see
`app/repos/models.py`'s `UtcDateTime` docstring). Changed to `sa.DateTime()`
below to match that precedent and keep this migration free of any
application-code import.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: str | Sequence[str] | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('roles_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    # ### end Alembic commands ###
